### ISSUE TITLE
Stop saying y-rich-text and yrt instead?

### ISSUE THREAD

**Issue by cphyc** [y-js/y-richtext#19]
because it's too long to type…

**Comment by dmonad** [comment]
I agree that it is long. Furthermore, y-rich-text looks kinda weird. But I have two reasons why we should keep y-rich-text:
- yrt, or y-rt is non-informative. Code style guides suggest not to do it, because it is confusing for third party developers. 
- The current naming convention for Yjs plugins is that every plugin starts with _y-_.

But we could name it _y-richtext_. And put it on `Y.RichText`? Is that better?

For variables, and between us we can continue to say yrt in my opinion.

For that matter, I suggest to rename rt-test -> richtext-test, and y-rt to y-richtext.

**Comment by cphyc** [comment]
We should have the same names for variable and files, shouldn't we? If
so, we can either chose y-richtext or y-rt (which is less informative
but shorter).
I can reopen #1 for that.

**Comment by dmonad** [comment]
Agreed, I think it is a good idea to reopen #1. I'm a big fan of short names, but y-rt is a bad choice, in my opinion.

**Comment by dmonad** [comment]
If we name it y-richtext, I'm going to rename this repository accordingly. (So you have to change the git origin)
https://help.github.com/articles/changing-a-remote-s-url/

**Comment by cphyc** [comment]
Ok, no problem.
