### ISSUE TITLE
Binding to editor(s)

### ISSUE THREAD

**Issue by dmonad** [y-js/y-richtext#28]
Find editors, that support the ot rich text format. Find a general way to bind the rich text type to them. (as described in the documentation)

**Comment by cphyc** [comment]
WIP on PR #38.

**Comment by cphyc** [comment]
I found Kune that uses OT types as a backend.

**Comment by dmonad** [comment]
Then there are also these:
- [ACE](http://ace.c9.io/)
- [codemirror](http://codemirror.net/)
- [atom](https://github.com/atom/atom)

**Comment by cphyc** [comment]
Atom is a tiny bit different since it doesn't rely on a web-browser, however, it would be really awesome to include collaborative edition within it!

**Comment by dmonad** [comment]
Just realized that neither ACE, codemirror, nor atom have richtext functionality. They just offer plain ol' text editing.

Quill still is currently the only good choice for richtext.

**Comment by humphd** [comment]
This is the only issue I can see in your repos that mentions CodeMirror, so I'll ask here.  How hard would it be to use a CodeMirror instance instead of ace or quill?  My use case is that we want to do collaboration across instances of Thimble (https://thimble.mozilla.org), which uses a forked version of Brackets, which uses CodeMirror internally.  Brackets wraps `CodeMirror` instances in an `Editor` abstraction, and I'm trying to find an appropriate OT or other collaboration tool I can inject/wrap around these.  We wrote a version of node's `fs` module for the browser (https://github.com/filerjs/filer) and this is how we do the filesystem in the browser--looking at your other repos here, it looks like we might be able to do sharing at that level, too.

Thanks for any guidance. cc @babhishek21

**Comment by dmonad** [comment]
Implementing support for CodeMirror would be a piece of cake. It would take me just a few hours, since Ace and CodeMirror share a similar API. Thimble seems to be an interesting project, so I'd be happy to do it.

You mentioned filerjs. I think you drew a connection to my "database adapter" repositories. In fact they have the same functionality as your storage providers. Let me know if you want a collaboration on that part.

**Comment by dmonad** [comment]
I just implemented CodeMirror support in [y-text](https://github.com/y-js/y-text)@9.3.0. I also added a [CodeMirror example](https://github.com/y-js/yjs/tree/11b30c707251a7d56385f6534350ead4a2ff6711/Examples/CodeMirror).

**Comment by babhishek21** [comment]
Thanks @dmonad . Works well. :+1:

**Comment by dmonad** [comment]
Great! You're welcome
