### ISSUE TITLE
Cursor position

### ISSUE THREAD

**Issue by cphyc** [y-js/y-richtext#9]
Y-rich-text should handle correctly cursors positions.

**Comment by dmonad** [comment]
This should be handled as a reference to a character.

I'm going to implement a new function on the list-type:

```
// Returns a reference to a word in the list
ref = List.prototype.getReference(i);  // i is a number
// you can call the following methods on a reference
ref.val() // returns the current value
ref.next // returns the reference to the next object (to the right) in the list
ref.prev // accordingly
```

Corentin will implement functionality for handling cursor positions
- Support for multiple users
- The cursor position(s) are propagated to all users
- When a user goes offline, the cursor position is not shown anymore.
- Find out how to get cursor positions from quill
- provide `setCursorPosition(i)` and `getCursorPosition()` method on the RichText type.
- provide a way to update the cursor position so that you don't have to search the whole document for the right reference. E.g.
  - go one position forward
  - go one position backward

**Comment by dmonad** [comment]
I implemented references as follows (read more on the y-list repository):

```
// Returns a reference to a word in the list
ref = List.prototype.ref(i);  // i is a number
// you can call the following methods on a reference
ref.val() // returns the current value
ref.getNext() // returns the reference to the next object (to the right) in the list
ref.getPrev() // accordingly
```

Now the cursor positions need to be implemented in the richtext type.

**Comment by cphyc** [comment]
Is their any support for setting the `ref`?

**Comment by dmonad** [comment]
What do you mean, exactly? Well, you can't change the reference to point to another object, if this is what you mean.

**Comment by cphyc** [comment]
WIP in branch 1d6870a.

**Comment by cphyc** [comment]
WIth the version from 1d6870a I get a weird issue. If I open two editors and move the cursor around, at some point some letters within y.val("editor")._model.val("characters") disappears *even though* I don't edit the text.
